#配置端口
server:
  port: 8080
  tcp:
    port: 18080
spring:
  #配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.159.215.31:3306/aiot-backstage?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  #Redis数据源
  redis:
    host: 139.159.215.31
    port: 6379
    timeout: 6000
    jedis:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      #连接池中的最大空闲连接
        min-idle: 5       #连接池中的最小空闲连接
# mybatis-plus相关配置
mybatis-plus:
  #  xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  #以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    #是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    #返回map时true:当查询数据为空时字段返回为null,false:不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true
    #这个配置会将执行的sql打印出来
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  微信小程序配置
wechat:
  app_id: wx3ef669658b5e2db2    #小程序 appId
  app_secret: 5cac2396266f612d3100f77bc71660f3   #小程序 appSecret
  grant_type: authorization_code #授权类型
  session_host: https://api.weixin.qq.com/sns/jscode2session
#  阿里云的形色
aliyun:
  host: https://plantapi.xingseapp.com
  path: /item/identification
  method: POST
  appCode: 1116529410564cfba495773bf9016d87
  contentType: application/x-www-form-urlencoded; charset=UTF-8
#  华为云文件资源管理 OBS
obs:
  ak: IOEWL9C4H0IAON6BWTOW
  sk: BxsIdXtz8aIJKNll6XMz4D6K00AXzichqi5nB4lX
  endPoint: https://obs.cn-north-4.myhuaweicloud.com
  bucketName: aiot-obs
  url: https://aiot-obs.obs.cn-north-4.myhuaweicloud.com/
dahua8900:
  ip: 192.168.2.243
  port: 9000
  username: system
  password: jyxt123456
gis:
  url: http://litecc.myds.me:9008/api/agriculture/warning
#=========微信公众号开发基本配置============
wx:
#微信公众号的appid
  appid: wxf1f1cb90e2e9cb20
#微信公众号的appsecret
  secret: e1426ee6c3ff9f3984db7854c7ba5303
#微信公众号的模板
  template: PPelW5xAJTQF3WsilLnX7fuYL2HiLh71Ccjc_a9X-QQ




